var MenuConfig =  [
    {
        title:"首页",
        key:"/admin/home"
    },
    {
        title:"UI",
        key:"/admin/ui",
        children:[
            {
                title:"按钮",
                key:"/admin/ui/buttons"
            },
            {
                title:"弹窗",
                key:'/admin/ui/modals'
            },
            {
                title:'loading',
                key:"/admin/ui/loading"
            },
            {
                title:"通知提醒",
                key:"/admin/ui/notification"
            },
            {
                title:"通知提醒",
                key:"/admin/ui/notification"
            },
            {
                title:"全局Message",
                key:"/admin/ui/messages"
            },
            {
                title:"Tab也签",
                key:"/admin/ui/tabs"
            },
            {
                title:"图片画廊",
                key:"/admin/ui/gallery"
            },
            {
                title:"轮播图",
                key:"/admin/ui/carousel"
            }

        ]
    },
    {
        title:"表单",
        key:"/admin/form",
        children:[
            {
                title:"登录",
                key:"/admin/form/login"
            },
            {
                title:"注册",
                key:"/admin/form/reg"
            }
        ]
    },
    {
        title:"表格",
        key:"/admin/table",
        children:[
            {
                title:"登录",
                key:"/admin/form/login"
            },
            {
                title:"注册",
                key:"/admin/form/reg"
            }
        ]
    }
]

export default MenuConfig